disabled_rules:
  - trailing_comma
  - identifier_name # Lots of math operations are written with short variable names as a standard
  - inclusive_language
included:
  - Sources
excluded:
  - .build
  - Pods
  - Packages
  - Sources/ImmutableXCore/Generated