name: Publish Cocoapods

on:
  push:
    tags:
      - '*'

jobs:
  unit_tests:
    runs-on: macos-12
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}