name: SwiftFormat

on:
  pull_request:
    branches:
      - '*'

jobs:
  SwiftFormat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sinoru/actions-setup-swift@v2
        with:
          swift-version: '5.7'
      - name: GitHub Action for SwiftFormat
        uses: CassiusPacheco/action-swiftformat@v0.1.0
        with:
          swiftformat-version: '0.50.2'