name: SwiftLint

on:
  pull_request:
    branches:
      - '*'

jobs:
  SwiftLint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          swiftlint --config .swiftlint.yml