name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  unit_tests:
    runs-on: macos-12
    steps:
    - name: Select Xcode 13.4.1
      run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme ImmutableXCore -destination "platform=iOS Simulator,OS=latest,name=iPhone 13"
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme ImmutableXCore -destination "platform=iOS Simulator,OS=latest,name=iPhone 13"
    - name: Run macOS tests
      run: set -o pipefail && swift test --enable-code-coverage
    - name: Parse coverage
      run: sh ./lcov.sh --build-path .build --target ImmutableXCorePackageTests.xctest --is-spm true --ignore-filename-regex ".build|Tests|Pods|Packages|Plugins|Generated|DerivedData|Signer.swift|ImmutableXHTTPLoggingLevel.swift|Constants.swift|Errors.swift"
      shell: bash
    - name: Publish to code climate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          coverage/lcov.info:lcov
        debug: true