name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  unit_tests:
    runs-on: macos-12
    steps:
    - name: Select Xcode 13.4.1
      run: sudo xcode-select -s "/Applications/Xcode_13.4.1.app"
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build for macOS
      run: set -o pipefail && swift build -v
    - name: Run macOS tests
      run: set -o pipefail && swift test -v
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme IMXCoreSDK -destination "platform=iOS Simulator,OS=latest,name=iPhone 13"
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme IMXCoreSDK -destination "platform=iOS Simulator,OS=latest,name=iPhone 13"